apiVersion: v1
kind: Service
metadata:
  name: crystal-backend
spec:
  selector:
    app: crystal-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crystal-backend
  labels:
    app: crystal-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crystal-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: crystal-backend
    spec:
      containers:
        - image: brentley/ecsdemo-crystal:latest
          resources:
            requests:
              memory: "16Mi"
              cpu: "5m"
            limits:
              memory: "32Mi"
              cpu: "10m"
          imagePullPolicy: Always
          name: crystal-backend
          ports:
            - containerPort: 3000
              protocol: TCP
