apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: brentley/ecsdemo-frontend:latest
          imagePullPolicy: Always
          name: frontend
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: CRYSTAL_URL
              value: "http://crystal-backend.default.svc.cluster.local/crystal"
            - name: NODEJS_URL
              value: "http://nodejs-backend.default.svc.cluster.local/"
