apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: crystal-backend-hpa
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: crystal-backend
  targetCPUUtilizationPercentage: 50
